### ISSUE TITLE
Fails to build with boost 1.45

### ISSUE THREAD

**Issue by hank** [udoprog/c10t#94]
They changed Boost.System and Boost.Filesystem enough to make the compile fail:

<pre>
[100%] Building CXX object src/CMakeFiles/c10t.dir/engine/isometric_engine.cpp.o
Linking CXX executable ../c10t
CMakeFiles/c10t.dir/main.cpp.o: In function `global constructors keyed to error':
  main.cpp:(.text+0x4ca4): undefined reference to `boost::system::generic_category()'
  main.cpp:(.text+0x4cb0): undefined reference to `boost::system::generic_category()'
  main.cpp:(.text+0x4cbc): undefined reference to `boost::system::system_category()'
</pre>
