### ISSUE TITLE
make c10t errors ! Halp !

### ISSUE THREAD

**Issue by pixartist** [udoprog/c10t#125]
well, see for yourself:

In file included from /home/minecraft/worldmaker/src/main.cpp:26:
/home/minecraft/worldmaker/src/threads/threadworker.hpp: In member function 'void threadworker<I, O>::run(int)':
/home/minecraft/worldmaker/src/threads/threadworker.hpp:168: error: void value not ignored as it ought to be
In file included from /home/minecraft/worldmaker/src/main.cpp:34:
/home/minecraft/worldmaker/src/global.hpp: In constructor 'settings_t::settings_t()':
/home/minecraft/worldmaker/src/global.hpp:88: error: 'hardware_concurrency' is not a member of 'boost::thread'
In file included from /home/minecraft/worldmaker/src/main.cpp:38:
/home/minecraft/worldmaker/src/fileutils.hpp: In member function 'bool dirlist::has_next(bool (_)(const std::string&))':
/home/minecraft/worldmaker/src/fileutils.hpp:55: error: 'is_regular_file' is not a member of 'fs'
/home/minecraft/worldmaker/src/main.cpp: In function 'bool do_one_world(settings_t&, world_info&, players_db&, warps_db&, const std::string&)':
/home/minecraft/worldmaker/src/main.cpp:433: error: 'is_regular_file' is not a member of 'fs'
/home/minecraft/worldmaker/src/main.cpp: In function 'int main(int, char__)':
/home/minecraft/worldmaker/src/main.cpp:1240: error: 'struct boost::filesystem::path' has no member named 'parent_path'
/home/minecraft/worldmaker/src/main.cpp:1495: error: 'struct boost::filesystem::path' has no member named 'parent_path'
/usr/include/boost/noncopyable.hpp: In copy constructor 'boost::thread::thread(const boost::thread&)':
/usr/include/boost/thread/thread.hpp:35:   instantiated from 'threadworker<I, O>::threadworker(int, int) [with I = render_job, O = render_result]'
/home/minecraft/worldmaker/src/main.cpp:159:   instantiated from here
/usr/include/boost/noncopyable.hpp:27: error: 'boost::noncopyable_::noncopyable::noncopyable(const boost::noncopyable_::noncopyable&)' is private
/usr/include/boost/thread/thread.hpp:35: error: within this context
/home/minecraft/worldmaker/src/threads/threadworker.hpp: In constructor 'threadworker<I, O>::threadworker(int, int) [with I = render_job, O = render_result]':
/home/minecraft/worldmaker/src/threads/threadworker.hpp:94: note: synthesized method 'boost::thread::thread(const boost::thread&)' first required here
/usr/include/boost/noncopyable.hpp: In member function 'boost::thread& boost::thread::operator=(const boost::thread&)':
/usr/include/boost/noncopyable.hpp:28: error: 'const boost::noncopyable_::noncopyable& boost::noncopyable_::noncopyable::operator=(const boost::noncopyable_::noncopyable&)' is private
/usr/include/boost/thread/thread.hpp:35: error: within this context
/home/minecraft/worldmaker/src/threads/threadworker.hpp: In constructor 'threadworker<I, O>::threadworker(int, int) [with I = render_job, O = render_result]':
/home/minecraft/worldmaker/src/threads/threadworker.hpp:94: note: synthesized method 'boost::thread& boost::thread::operator=(const boost::thread&)' first required here
make[3]: *_\* [src/CMakeFiles/c10t.dir/main.o] Error 1
make[2]: **\* [src/CMakeFiles/c10t.dir/all] Error 2
make[1]: **\* [src/CMakeFiles/c10t.dir/rule] Error 2

Tried to compile on Ubuntu 8.0.4
